name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Docker Login
      run: docker login docker.io -u ${{ secrets.USERNAME }} -p ${{ secrets.PASSWORD }}
    - name: Docker build
      run: |
        docker build -t spring-cicd .
        docker tag spring-cicd choijungwoo123/cicdtest:${GITHUB_SHA::7}
        docker push choijungwoo123/cicdtest:${GITHUB_SHA::7}